### PR TITLE
Added sentence card types.

### PR DESCRIPTION
**Pull request by nking-1**
New cards are Japanese sentence -> English sentence and vice-versa. Cards include audio and images of the sentence text.

Learning words in context is extremely important. In my opinion the example sentences are one of the best parts of the Genki app. Turning the sentences into flashcards is a surefire way to learn the true meaning of the words as well as practice grammar.

The downside to this change is that there are now thousands more cards in the deck, but it's easy enough to delete the card types you don't want through Anki's card editor.

### CODE REVIEW

**Comment by jmatth** [comment]
Cool, thanks for the patch. Just a couple things before I merge it:

1. Not sure if you care, but the commit has your email as `thellias@Nicholass-MacBook-Pro.local`, so github won't link it back to your account once it's merged.

2. As is, the new sentence cards aren't getting added even though they're part of the model. This is really on me for how hacky the database generation is. I pushed a commit to master that makes fixing it easier, just rebase and bump `NUM_CARDS` in `apkg.py` to 5 and it should work. I could also just do this myself on the command line if you don't care about fixing the first point.

**Comment by nking-1** [comment]
Thanks for pointing out that the email was incorrect. I'll try to fix that tonight.

When I loaded the deck into Anki I noticed the bug where the cards are not added correctly. I'm glad the fix was easy. I think something cool that could be done in the future is to add command line options that specify which kinds of cards you want, since 5 cards per note makes a huge deck. It's not that important, though, because you can always just delete the cards you don't want after you import the deck.

**Comment by nking-1** [comment]
I've updated the email address for this commit

**Comment by jmatth** [comment]
Merged manually via the command line so closing this PR. Thanks again for contributing!

**Pull request closed without merging**
